import { db } from "@/lib/db";
import { generateFix, StackFrameInput, CulpritCommitInput } from "@/lib/ai/generate-fix";
import {
  parseOwnerRepo,
  createBranch,
  commitFileChanges,
  createPullRequest,
  getDefaultBranch,
} from "@/lib/github/client";

export interface GenerateAndOpenFixInput {
  incident: {
    id: string;
    title: string;
    errorMessage: string;
  };
  stackFrames: StackFrameInput[];
  culpritCommit: CulpritCommitInput;
  culpritDiff: string;
  projectRepoUrl: string;
}

export interface ApplyFixResult {
  success: boolean;
  prUrl?: string;
  branchName?: string;
  error?: string;
}

export async function generateAndOpenFix({
  incident,
  stackFrames,
  culpritCommit,
  culpritDiff,
  projectRepoUrl,
}: GenerateAndOpenFixInput): Promise<ApplyFixResult> {
  // Add AuditLog: Hotfix generation started
  try {
    await db.auditLog.create({
      data: {
        incidentId: incident.id,
        type: "HOTFIX_START",
        message: "Hotfix generation started",
      },
    });
  } catch (logErr) {
    console.warn("Failed to log hotfix start audit event:", logErr);
  }

  // 1. Generate patch with Gemini
  const fixResult = await generateFix({
    errorMessage: incident.errorMessage,
    stackFrames,
    culpritCommit,
    culpritDiff,
    projectRepoUrl,
  });

  if (!fixResult || fixResult.files.length === 0) {
    const errorMsg = "Gemini AI was unable to generate a valid code patch.";
    console.warn(`[Apply Fix] ${errorMsg}`);

    await db.fix.create({
      data: {
        incidentId: incident.id,
        diff: "// Patch generation failed",
        prDescription: errorMsg,
        status: "FAILED",
      },
    });

    await db.auditLog.create({
      data: {
        incidentId: incident.id,
        type: "HOTFIX_FAILED",
        message: `Hotfix generation failed: ${errorMsg}`,
      },
    });

    return { success: false, error: errorMsg };
  }

  // Intermediate state FIX_GENERATED: patch generation succeeded, proceeding to PR creation
  try {
    const { transitionIncident } = await import("@/lib/workflow/status");
    await transitionIncident(incident.id, "FIX_GENERATED", "system");
  } catch (tErr) {
    console.warn("[Apply Fix] Failed setting status to FIX_GENERATED:", tErr);
  }

  // 2. Parse repo
  const parsedRepo = parseOwnerRepo(projectRepoUrl);
  if (!parsedRepo) {
    const errorMsg = `Invalid repository URL format "${projectRepoUrl}".`;
    console.warn(`[Apply Fix] ${errorMsg}`);

    await db.fix.create({
      data: {
        incidentId: incident.id,
        diff: "// Repository invalid",
        prDescription: errorMsg,
        status: "FAILED",
      },
    });

    await db.auditLog.create({
      data: {
        incidentId: incident.id,
        type: "HOTFIX_FAILED",
        message: `Hotfix generation failed: ${errorMsg}`,
      },
    });

    return { success: false, error: errorMsg };
  }

  const { owner, repo } = parsedRepo;
  const shortId = incident.id.slice(-6);
  const branchName = `patchwork/fix-${shortId}-${Date.now().toString(36).slice(-4)}`;

  try {
    // 3. GitHub Operations: Branch -> Commit -> Pull Request
    const baseBranch = await getDefaultBranch(owner, repo);
    await createBranch(owner, repo, branchName, baseBranch);

    await commitFileChanges(
      owner,
      repo,
      branchName,
      fixResult.files.map((f) => ({
        path: f.path,
        newContent: f.newContent,
        sha: f.existingSha,
      }))
    );

    const prResult = await createPullRequest(
      owner,
      repo,
      branchName,
      baseBranch,
      fixResult.prTitle,
      `${fixResult.prDescription}\n\n---\n*Automated Hotfix generated by [Patchwork AI](https://github.com).*`
    );

    // Build diff summary for DB storage
    const diffSummary = fixResult.files
      .map(
        (f) =>
          `--- a/${f.path}\n+++ b/${f.path}\n// Automated full-file patch applied (${f.newContent.split("\n").length} lines)`
      )
      .join("\n\n");

    // 4. Save Fix record in DB with PR_OPENED status
    await db.fix.create({
      data: {
        incidentId: incident.id,
        diff: diffSummary,
        prUrl: prResult.prUrl,
        prNumber: prResult.prNumber,
        prTitle: fixResult.prTitle,
        prDescription: fixResult.prDescription,
        branchName: branchName,
        status: "PR_OPENED",
      },
    });

    // 5. Update Incident status to IN_REVIEW via status workflow
    const { transitionIncident } = await import("@/lib/workflow/status");
    const updatedIncident = await transitionIncident(incident.id, "IN_REVIEW", "system");

    // 6. Add AuditLog & emit HOTFIX_PR_OPENED event
    await db.auditLog.create({
      data: {
        incidentId: incident.id,
        type: "HOTFIX_OPENED",
        message: `Hotfix PR opened: ${prResult.prUrl}`,
      },
    });

    const { emitEvent } = await import("@/lib/events/dispatcher");
    if (updatedIncident.project?.org) {
      emitEvent({
        type: "HOTFIX_PR_OPENED",
        payload: {
          incident: updatedIncident,
          org: updatedIncident.project.org,
          prUrl: prResult.prUrl,
          branchName,
        },
      });
    }

    return {
      success: true,
      prUrl: prResult.prUrl,
      branchName,
    };
  } catch (gitErr: any) {
    const errorMsg = gitErr?.message || "Failed to commit changes or open PR on GitHub.";
    console.error(`[Apply Fix] GitHub operations failed for incident ${incident.id}:`, errorMsg);

    await db.fix.create({
      data: {
        incidentId: incident.id,
        diff: "// GitHub PR creation failed",
        prDescription: errorMsg,
        branchName: branchName,
        status: "FAILED",
      },
    });

    await db.auditLog.create({
      data: {
        incidentId: incident.id,
        type: "HOTFIX_FAILED",
        message: `Hotfix generation failed: ${errorMsg}`,
      },
    });

    return {
      success: false,
      error: errorMsg,
    };
  }
}
