"use client";

import React from "react";
import { ShieldCheck, GitPullRequest, Activity, Key } from "lucide-react";

export function SafetySection() {
  const safeguards = [
    {
      title: "PR-Only Delivery Model",
      desc: "Every fix generated by Gemini ships strictly as a GitHub Pull Request. Patchwork never merges code into production automatically without human developer sign-off.",
      icon: GitPullRequest,
      badge: "NON-DESTRUCTIVE",
    },
    {
      title: "Confidence-Scored Root Cause Isolation",
      desc: "Commit topology scoring evaluates git history to ensure high confidence before patch generation. Low-confidence anomalies are flagged for manual operator review.",
      icon: ShieldCheck,
      badge: "PRECISION GATED",
    },
    {
      title: "Full Audit Trail for Every Action",
      desc: "Every exception payload, triage event, commit isolation score, diff generation, and status change is immutably logged in system audit records.",
      icon: Activity,
      badge: "COMPLIANT LOGS",
    },
    {
      title: "Scoped & Revocable API Tokens",
      desc: "Connect webhooks with cryptographically generated API keys. Revoke tokens instantly at any time to restrict ingestion streams across organizations.",
      icon: Key,
      badge: "ZERO TRUST ACCESS",
    },
  ];

  return (
    <section
      id="safety"
      className="py-20 bg-[#08090a] font-mono text-[#c9d1d9] console-scanlines border-b border-zinc-800/80"
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        {/* Section Header */}
        <div className="text-center space-y-2.5">
          <div className="text-xs font-mono font-bold text-emerald-400 uppercase tracking-widest">
            // ENTERPRISE SAFEGUARDS
          </div>
          <h2 className="text-2xl sm:text-4xl font-bold text-zinc-100 uppercase tracking-wide">
            Engineered for Production Safety & Trust
          </h2>
          <p className="text-xs sm:text-sm text-zinc-400 max-w-2xl mx-auto leading-relaxed">
            Autonomous intelligence with zero risk of unvetted code deployment.
          </p>
        </div>

        {/* Safeguards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {safeguards.map((card, idx) => {
            const Icon = card.icon;
            return (
              <div
                key={idx}
                className="p-6 rounded-xl border border-zinc-800 bg-[#0d0f12] space-y-4 shadow-xl console-scanlines hover:border-zinc-700 transition-all flex flex-col justify-between"
              >
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="p-2 rounded bg-emerald-950/40 border border-emerald-800/60 text-emerald-400">
                      <Icon className="w-5 h-5" />
                    </div>
                    <span className="text-[10px] font-mono font-bold text-emerald-300 bg-emerald-950/80 border border-emerald-800 px-2 py-0.5 rounded">
                      {card.badge}
                    </span>
                  </div>

                  <h3 className="text-base font-bold text-zinc-100 uppercase tracking-wide">
                    {card.title}
                  </h3>

                  <p className="text-xs text-zinc-400 leading-relaxed font-mono">
                    {card.desc}
                  </p>
                </div>

                <div className="pt-3 border-t border-zinc-800/80 text-[10px] text-zinc-500 font-mono flex items-center justify-between">
                  <span>policy_enforcement: strict</span>
                  <span className="text-emerald-400">VERIFIED</span>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
